//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeDadosDeJogos.Models
{
    using System;
    using System.Data.Entity.Infrastructure;
    using Microsoft.EntityFrameworkCore;

    public partial class GameModelContainer : DbContext
    {
        public GameModelContainer(DbContextOptions<GameModelContainer> options)
            : base(options)
        {
        }
    
        public virtual DbSet<Game> Games1 { get; set; }
    }
}
